/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarContaRouteImport } from './routes/recuperar-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as CatalogoOficialRouteImport } from './routes/catalogo-oficial'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceitaIdRouteImport } from './routes/receita.$id'
import { Route as PerfilUsernameRouteImport } from './routes/perfil.$username'
import { Route as AuthenticatedPublicarReceitaRouteImport } from './routes/_authenticated/publicar-receita'
import { Route as AuthenticatedPesquisaRouteImport } from './routes/_authenticated/pesquisa'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMinhasReceitasRouteImport } from './routes/_authenticated/minhas-receitas'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedComunidadeRouteImport } from './routes/_authenticated/comunidade'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPerfilEditarRouteImport } from './routes/_authenticated/perfil.editar'
import { Route as AuthenticatedEditarReceitaIdRouteImport } from './routes/_authenticated/editar-receita.$id'
import { Route as AuthenticatedAdminUtilizadoresRouteImport } from './routes/_authenticated/admin/utilizadores'
import { Route as AuthenticatedAdminPendentesRouteImport } from './routes/_authenticated/admin/pendentes'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin/notificacoes'
import { Route as AuthenticatedAdminCatalogoRouteImport } from './routes/_authenticated/admin/catalogo'

const RecuperarContaRoute = RecuperarContaRouteImport.update({
  id: '/recuperar-conta',
  path: '/recuperar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoOficialRoute = CatalogoOficialRouteImport.update({
  id: '/catalogo-oficial',
  path: '/catalogo-oficial',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitaIdRoute = ReceitaIdRouteImport.update({
  id: '/receita/$id',
  path: '/receita/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilUsernameRoute = PerfilUsernameRouteImport.update({
  id: '/perfil/$username',
  path: '/perfil/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPublicarReceitaRoute =
  AuthenticatedPublicarReceitaRouteImport.update({
    id: '/publicar-receita',
    path: '/publicar-receita',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPesquisaRoute = AuthenticatedPesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinhasReceitasRoute =
  AuthenticatedMinhasReceitasRouteImport.update({
    id: '/minhas-receitas',
    path: '/minhas-receitas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComunidadeRoute = AuthenticatedComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPerfilEditarRoute =
  AuthenticatedPerfilEditarRouteImport.update({
    id: '/perfil/editar',
    path: '/perfil/editar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEditarReceitaIdRoute =
  AuthenticatedEditarReceitaIdRouteImport.update({
    id: '/editar-receita/$id',
    path: '/editar-receita/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUtilizadoresRoute =
  AuthenticatedAdminUtilizadoresRouteImport.update({
    id: '/utilizadores',
    path: '/utilizadores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPendentesRoute =
  AuthenticatedAdminPendentesRouteImport.update({
    id: '/pendentes',
    path: '/pendentes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogoRoute =
  AuthenticatedAdminCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo-oficial': typeof CatalogoOficialRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/recuperar-conta': typeof RecuperarContaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/minhas-receitas': typeof AuthenticatedMinhasReceitasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/publicar-receita': typeof AuthenticatedPublicarReceitaRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/receita/$id': typeof ReceitaIdRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/pendentes': typeof AuthenticatedAdminPendentesRoute
  '/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/editar-receita/$id': typeof AuthenticatedEditarReceitaIdRoute
  '/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo-oficial': typeof CatalogoOficialRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/recuperar-conta': typeof RecuperarContaRoute
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/minhas-receitas': typeof AuthenticatedMinhasReceitasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/publicar-receita': typeof AuthenticatedPublicarReceitaRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/receita/$id': typeof ReceitaIdRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/pendentes': typeof AuthenticatedAdminPendentesRoute
  '/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/editar-receita/$id': typeof AuthenticatedEditarReceitaIdRoute
  '/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/catalogo-oficial': typeof CatalogoOficialRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/recuperar-conta': typeof RecuperarContaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/comunidade': typeof AuthenticatedComunidadeRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/minhas-receitas': typeof AuthenticatedMinhasReceitasRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pesquisa': typeof AuthenticatedPesquisaRoute
  '/_authenticated/publicar-receita': typeof AuthenticatedPublicarReceitaRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/receita/$id': typeof ReceitaIdRoute
  '/_authenticated/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/pendentes': typeof AuthenticatedAdminPendentesRoute
  '/_authenticated/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/_authenticated/editar-receita/$id': typeof AuthenticatedEditarReceitaIdRoute
  '/_authenticated/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo-oficial'
    | '/criar-conta'
    | '/login'
    | '/recuperar-conta'
    | '/admin'
    | '/comunidade'
    | '/favoritos'
    | '/minhas-receitas'
    | '/notificacoes'
    | '/pesquisa'
    | '/publicar-receita'
    | '/perfil/$username'
    | '/receita/$id'
    | '/admin/catalogo'
    | '/admin/notificacoes'
    | '/admin/pendentes'
    | '/admin/utilizadores'
    | '/editar-receita/$id'
    | '/perfil/editar'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo-oficial'
    | '/criar-conta'
    | '/login'
    | '/recuperar-conta'
    | '/comunidade'
    | '/favoritos'
    | '/minhas-receitas'
    | '/notificacoes'
    | '/pesquisa'
    | '/publicar-receita'
    | '/perfil/$username'
    | '/receita/$id'
    | '/admin/catalogo'
    | '/admin/notificacoes'
    | '/admin/pendentes'
    | '/admin/utilizadores'
    | '/editar-receita/$id'
    | '/perfil/editar'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/catalogo-oficial'
    | '/criar-conta'
    | '/login'
    | '/recuperar-conta'
    | '/_authenticated/admin'
    | '/_authenticated/comunidade'
    | '/_authenticated/favoritos'
    | '/_authenticated/minhas-receitas'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pesquisa'
    | '/_authenticated/publicar-receita'
    | '/perfil/$username'
    | '/receita/$id'
    | '/_authenticated/admin/catalogo'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/pendentes'
    | '/_authenticated/admin/utilizadores'
    | '/_authenticated/editar-receita/$id'
    | '/_authenticated/perfil/editar'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CatalogoOficialRoute: typeof CatalogoOficialRoute
  CriarContaRoute: typeof CriarContaRoute
  LoginRoute: typeof LoginRoute
  RecuperarContaRoute: typeof RecuperarContaRoute
  PerfilUsernameRoute: typeof PerfilUsernameRoute
  ReceitaIdRoute: typeof ReceitaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-conta': {
      id: '/recuperar-conta'
      path: '/recuperar-conta'
      fullPath: '/recuperar-conta'
      preLoaderRoute: typeof RecuperarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo-oficial': {
      id: '/catalogo-oficial'
      path: '/catalogo-oficial'
      fullPath: '/catalogo-oficial'
      preLoaderRoute: typeof CatalogoOficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receita/$id': {
      id: '/receita/$id'
      path: '/receita/$id'
      fullPath: '/receita/$id'
      preLoaderRoute: typeof ReceitaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$username': {
      id: '/perfil/$username'
      path: '/perfil/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof PerfilUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/publicar-receita': {
      id: '/_authenticated/publicar-receita'
      path: '/publicar-receita'
      fullPath: '/publicar-receita'
      preLoaderRoute: typeof AuthenticatedPublicarReceitaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pesquisa': {
      id: '/_authenticated/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof AuthenticatedPesquisaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minhas-receitas': {
      id: '/_authenticated/minhas-receitas'
      path: '/minhas-receitas'
      fullPath: '/minhas-receitas'
      preLoaderRoute: typeof AuthenticatedMinhasReceitasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comunidade': {
      id: '/_authenticated/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof AuthenticatedComunidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/perfil/editar': {
      id: '/_authenticated/perfil/editar'
      path: '/perfil/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof AuthenticatedPerfilEditarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editar-receita/$id': {
      id: '/_authenticated/editar-receita/$id'
      path: '/editar-receita/$id'
      fullPath: '/editar-receita/$id'
      preLoaderRoute: typeof AuthenticatedEditarReceitaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/utilizadores': {
      id: '/_authenticated/admin/utilizadores'
      path: '/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AuthenticatedAdminUtilizadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pendentes': {
      id: '/_authenticated/admin/pendentes'
      path: '/pendentes'
      fullPath: '/admin/pendentes'
      preLoaderRoute: typeof AuthenticatedAdminPendentesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalogo': {
      id: '/_authenticated/admin/catalogo'
      path: '/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCatalogoRoute: typeof AuthenticatedAdminCatalogoRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminPendentesRoute: typeof AuthenticatedAdminPendentesRoute
  AuthenticatedAdminUtilizadoresRoute: typeof AuthenticatedAdminUtilizadoresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCatalogoRoute: AuthenticatedAdminCatalogoRoute,
  AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
  AuthenticatedAdminPendentesRoute: AuthenticatedAdminPendentesRoute,
  AuthenticatedAdminUtilizadoresRoute: AuthenticatedAdminUtilizadoresRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedComunidadeRoute: typeof AuthenticatedComunidadeRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedMinhasReceitasRoute: typeof AuthenticatedMinhasReceitasRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPesquisaRoute: typeof AuthenticatedPesquisaRoute
  AuthenticatedPublicarReceitaRoute: typeof AuthenticatedPublicarReceitaRoute
  AuthenticatedEditarReceitaIdRoute: typeof AuthenticatedEditarReceitaIdRoute
  AuthenticatedPerfilEditarRoute: typeof AuthenticatedPerfilEditarRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedComunidadeRoute: AuthenticatedComunidadeRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedMinhasReceitasRoute: AuthenticatedMinhasReceitasRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPesquisaRoute: AuthenticatedPesquisaRoute,
  AuthenticatedPublicarReceitaRoute: AuthenticatedPublicarReceitaRoute,
  AuthenticatedEditarReceitaIdRoute: AuthenticatedEditarReceitaIdRoute,
  AuthenticatedPerfilEditarRoute: AuthenticatedPerfilEditarRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CatalogoOficialRoute: CatalogoOficialRoute,
  CriarContaRoute: CriarContaRoute,
  LoginRoute: LoginRoute,
  RecuperarContaRoute: RecuperarContaRoute,
  PerfilUsernameRoute: PerfilUsernameRoute,
  ReceitaIdRoute: ReceitaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
